name: persian_datetime_picker
description: A persian (farsi,shamsi) datetime picker for flutter, inspired by material datetime picker.
version: 1.0.6
author: Mohammad amir mohammdi <mem.amir.m@gamil.com>
homepage: https://github.com/M-amir-M/persian-datetime-picker

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shamsi_date: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

